version: '2'

services:
  app:
    image: "education:latest"
    build:
      context:  .
    container_name: app
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/education
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=education
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
volumes:
  db: